### ISSUE TITLE
Labels get accidentially associated with selectmenu when selectmenu has no id

### ISSUE THREAD

**Issue by cburgdorf** [fnagel/jquery-ui#101]
This can easily be fixed:

 // set a default id value

var selectmenuId = this.element.attr('id') || 'ui-selectmenu-' + Math.random().toString(16).slice(2, 10);

 // set a default id value (...and change the previous comment to "generate a default id value") ;-)

this.element.attr('id', selectmenuId);

**Comment by fnagel** [comment]
I need to test this, thanks for your contribution!

**Comment by fnagel** [comment]
Am I right you are set an ID to the original select element? 

Please explain to me in which scenario the label (which one? The label of an optgroup?) will get associated with the original select element.

**Comment by cburgdorf** [comment]
I experienced the problem that if you have a basic select element without an ID and then call selectmenu(), all <label> tags on the entire page get "label for xxx" markup attached.

When I had a look at your code, I noticed that you deal with the case that the select element comes without an ID and generate a random one. However it is not set on the select element itself. Once you change this, the bug appears to be fixed.

Unfortunatly, I wasn't able to reproduce it in a fiddle. Maybe I need to investigate a bit more about it.

**Comment by fnagel** [comment]
Sorry about the long waiting time, but I had an surgery and was not able to work on the selectmenu widget the last few weeks. I will take a look asap, please be patient!

**Comment by fnagel** [comment]
Im not able to reproduce your issue. Please provide a demo zip or a link if its not reproducable in a fiddle.
Its set to the generated a tag andthe menu div, take a look at the var this.ids

**Comment by Ryzo** [comment]
I just came across this problem myself so I can give you a bit more information.

I think the problem you having reproducing it is because this only seems to impact IE7 (it might be IE 6 as well) 

Anyway, after a bit of hunting around I found the offending piece of code:

// make associated form label trigger focus
$('label[for="' + this.element.attr('id') + '"]')
    <other code here>

There are a couple of things going on here..
Firstly, if you don't have an id then jquery is looking for $('label[for=""]').  In IE 7 at least the selector incorrectly returns all labels. Other browsers however seem to do this correctly and select only the labels with a blank FOR attribute,hence why you don't get the problem in other browsers. (unless you have a label with a blank FOR attribute)

The other issue ,which is the real problem, is that it's looking for the id which obviously doesn't exist. There is code above it that tries to handle no ids by assigning it a random one but it doesn't flow on to that piece of code. 

The following code change fixed the problem for me. 

// make associated form label trigger focus
$('label[for="' + selectmenuId + '"]')
    <other code here>

Hopefully that makes sense. If you need a demo I'm sure I can write one up quickly.

Cheers

**Comment by cburgdorf** [comment]
Man, I'm glad you jumped on the train because I'm too busy investigating it any further at the moment. Sorry, for my unresponsiveness..

**Comment by cburgdorf** [comment]
Sorry, didnt mean to close the issue. Reopened it.

**Comment by fnagel** [comment]
@Ryzo
It makes 100% sense. Fixed and committed. Thanks for your help.

@cburgdorf
Are you able to confirm this patch? Please test the latest version!

**Comment by cburgdorf** [comment]
Confirmed, closing this issue.

**Comment by fnagel** [comment]
@Ryzo
@cburgdorf
Thanks for your feedback and support!
