### ISSUE TITLE
Update to jQuery 1.6.x

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#118]
This is not needed before all official jQuery UI widgets work with 1.6.x

General help:
http://blog.jquery.com/2011/05/03/jquery-16-released/
http://blog.jquery.com/2011/05/12/jquery-1-6-1-released/

Problem with new prop method (replaces attr ?), see http://filamentgroup.com/lab/jquery_ui_selectmenu_an_aria_accessible_plugin_for_styling_a_html_select/#commentNumber331

**Comment by tauren** [comment]
With jQuery 1.6.2 , I'm getting an `Uncaught TypeError: Cannot call method 'unbind' of undefined` at line 453. I don't have this problem in jQuery 1.5.2. 

https://github.com/fnagel/jquery-ui/blob/selectmenu/ui/jquery.ui.selectmenu.js#L453

My page layout is such that I do not have labels on my selects. I haven't tested it with labels.

**Comment by tauren** [comment]
The following seems to solve the problem, but I didn't really spend much time figuring out what was causing the issue in the first place. So it might be worth a little more investigation.

```
    // unbind click on label, reset its for attr
    var lbl = $( 'label[for=' + this.newelement.attr('id') + ']' )
        .attr( 'for', this.element.attr( 'id' ) );
    if (lbl) {
        lbl.unbind( '.selectmenu' );
    }
```

See this commit:
https://github.com/tauren/jquery-ui/commit/aa337a6878de8e765a9db6c76e824c7b83a57604

**Comment by fnagel** [comment]
Did you check this issue: #115

**Comment by tauren** [comment]
Is #115 really related to this? I'm super busy and don't have the time right now to apply the commit in #115 and test. But from a quick look at the commit, I'm not convinced it deals with this problem.

BTW, sorry, I didn't mean to hijack this issue. I'm not sure why it was working in 1.5.2 and not in 1.6.2. But I can't guarantee that it is that upgrade that is causing the problem. It could very well be the update in jquery-ui causing the problem. So I should have created a new issue. 

Bottom line is the following selectmenu code at line 453 used to execute in a 1.5.2 environment without failing:

```
$( 'label[for=' + this.newelement.attr('id') + ']' )
    .attr( 'for', this.element.attr( 'id' ) )
    .unbind( '.selectmenu' );
```

But in 1.6.2 with the latest jquery-ui, it now fails because the call to `attr()` returns `undefined`. This hack fixes it, but I haven't gotten to the bottom of what caused the problem to happen.

```
// unbind click on label, reset its for attr
var lbl = $( 'label[for=' + this.newelement.attr('id') + ']' )
    .attr( 'for', this.element.attr( 'id' ) );
lbl && lbl.unbind( '.selectmenu' );
```

**Comment by betalb** [comment]
jQuert UI 1.8.16 ships with jQuery 1.6.2
they added propAttr method to jQuery

But the issue described above caused by another reason. jQuery now returns undefined if attribute doesn't exist, so attr method works like getter and returns string or undefined

**Comment by fnagel** [comment]
Working on v1.2 shipping with latest jQuery UI stable versions.

These currently are: jQuery 1.6.2 and jQuery UI 1.8.16

**Comment by fnagel** [comment]
Ive updated the code and have no issues found yet. This would be according to the update guide. "jQuery 1.6.1 will allow you to use .attr() just as it was used before in all situations." See: http://blog.jquery.com/2011/05/12/jquery-1-6-1-released/

Please test and report!

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed!

**Comment by betalb** [comment]
I've rechecked, It seems that described error is fixed

**Comment by fnagel** [comment]
Nice, thanks for the feedback!
