### ISSUE TITLE
Not hiding selectmenu content text when selected

### ISSUE THREAD

**Issue by lephyrius** [fnagel/jquery-ui#127]
You are not hiding the selectmenu content when the item is selected.
I have created a jsfiddle:
http://jsfiddle.net/ewG7T/1/
As you can see the glowing red description text is visible when the item is selected.
It works in Opera 11.11 so maybe you have only tested in that browser. :)
Not working in:
Safari 5.0.5
Chrome 11
Firefox 4

**Comment by fnagel** [comment]
Im sorry, but the fiddle is working pefect for me in FF4 and latest Chrome
expect for some red glowing border whoch is visible. This is not a bug  but
needs some CSS adjustment.
Can you provide a screenshot?

**Comment by lephyrius** [comment]
Here is the screenshot:
http://dl.dropbox.com/u/21367866/glow%20illustration.png

What kind of adjustments does the CSS need?
Note I made the glow larger to be able to see it easily.

Here is Opera:
http://dl.dropbox.com/u/21367866/Opera%20Glow.png
It may be because Opera got a bad glow effect on how it should work.(I think)

**Comment by fnagel** [comment]
Ahh, now I've got an idea what you're talking about :-)

This problem is based upon a very custom usage. First you need to use the format option, which is a "nice-to-have" feature and will be changed soon with the jQuery template plugin (see your issue: https://github.com/fnagel/jquery-ui/issues/106). Additional you need a custom CSS which makes the visual border (or etc.) cross the border of two options.

Im currently not willing to change something in order to fix this issue. Just use something like this: 

<pre>
.ui-selectmenu-menu span.ui-selectmenu-item-content.glow {
    text-shadow: 0;
    color:#F00;
}
.ui-selectmenu-open span.ui-selectmenu-item-content.glow {
    text-shadow: 0 0 14px #F00;   
}
</pre>

Demo: http://jsfiddle.net/ewG7T/6/

**Comment by fnagel** [comment]
There are currently issues with CSS files via GitHub, so please use this fiddle instead: http://jsfiddle.net/ewG7T/7/

Please give feedback!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by lephyrius** [comment]
It works and it is a bit custom usage so I understand it won't be implemented.

**Comment by fnagel** [comment]
Thanks for the feedback. Closed.
