### ISSUE TITLE
Selectmenu dropdown doesn't hide when I scroll element with overflow: auto

### ISSUE THREAD

**Issue by betalb** [fnagel/jquery-ui#13]
If I have <select> inside a block with fixed height and overflow set to auto, opened selectmenu always stays in the same place when I scroll this block.

Default <select> just hides dropdown at mousewheel (at least in ff & chrome)

**Comment by betalb** [comment]
here is the link to example
http://github.com/betalb/attachments/raw/master/selectmenu.example.zip

**Comment by fnagel** [comment]
Ok, this is a problem. Im not sure how to solve this. Perhaps I could fix this when Im changing the positioning mechanism, please see: http://github.com/fnagel/jquery-ui/issues#issue/3

**Comment by tauren** [comment]
I'm running into this problem too. Perhaps a quick solution is to detect the scroll event and just close the selectmenu when scroll has happened? 

$container.scroll(function() {
  $selectmenu.close();
}

This is untested code just to illustrate the concept.

**Comment by tauren** [comment]
This demo illustrates how to close the selectmenu on the scroll of a container. For me, it solves the immediate problem, even though it isn't terribly elegant:
https://github.com/tauren/jquery-ui/blob/selectmenu/demos/selectmenu/positioning.html

To really solve the problem within the plugin, I'm willing to bet that this is the problem:
- When a selectmenu is created, the popup menu is added to the end of the BODY.
- The popup is absolutely positioned on the page.
- The demos work when you scroll the body because the popup is contained within the scrolling element (the page) and is absolutely positioned on that page, so scrolling the page moves the element.
- Putting a selectmenu into any scrolling container besides the body will cause problems because that container does not have the popup inside of it

What needs to happen is the popup should be added alongside where the real select is at and it should be relatively positioned. This will mean playing with CSS values to get it working, but I think it should work.

This is just conjecture at the moment, I could be mistaken.

**Comment by fnagel** [comment]
@tauren
I would say you outlined the problem pretty good. The problem is that the popup needs to be positioned at the end of the body so its able to overlay all other elements (IE and probably others). 

The quick fix seems to work, thanks!

Did you tried a similar configuration when using the position plugin?

**Comment by tauren** [comment]
@fnagel: yes, I realized while working on the problem that positioning the selectmenu popup next to the select probably wouldn't work. Although it would scroll with the text, It would cause part of the popup to be hidden as the scroll window was moved. I'm not sure if using a higher z-index would solve the problem or not, as I did not test this.

The quick fix does work, and works well, but it is an external fix. It would be nice to get it working within the selectmenu plugin, but I haven't given any thought yet on how to do that.

I haven't done anything with selectmenu and the position plugin yet. It sounded like you were already heading down that path and didn't want to be duplicating effort.

**Comment by fnagel** [comment]
@tauren
Believe me, z-index will not fix the issue. Take a look at any pop-up / dialog script.

I've already have a working version with position support, but I need to implement optiosn like style:'dropdown'. I'm currently thinking of the style option as a pure CSS switch and a positionPara option to overwrite the default positioning. This way it would be possible to use any positioning you like!

BACK TO TOPIC
@betalb
I will not fix this issue till the position plugin is implemented. If the problem persists I will give it a try.

**Comment by tauren** [comment]
Yeah, I didn't think z-index would solve it. Glad to hear you're making progress with the position plugin! I like the idea of positioning anywhere based on CSS, but hope that by default it will work as expected.

**Comment by fnagel** [comment]
Please check out the latest commit. I've implemented the jQuery UI position plugin. Any feedback is appreciated.

**Comment by fnagel** [comment]
Closed. Please reopen if there are still problems.
