### ISSUE TITLE
Selectmenu should update its dropdown height on content update

### ISSUE THREAD

**Issue by trollixx** [fnagel/jquery-ui#133]
For example, deleting some items from selectmenu doesn't force recalculation of its height. Calling $("#el").selectmenu() doesn't do the thing too.

**Comment by fnagel** [comment]
Im not able to reproduce your issue. In which browsers does this problem occur? Are you able to provide a demo? Please see here: https://github.com/fnagel/jquery-ui/issues/61

**Comment by trollixx** [comment]
Just now got this bug in:
- Chromium 13.0.782.20
- Firefox 4 & 5
- Opera 11.11

Playing with jsfiddle to provide a demo....

**Comment by fnagel** [comment]
Ive tested in FF4 & Chrome too, without problems. I'll waiting for the demo
fiddle :-)

**Comment by trollixx** [comment]
Got It! http://jsfiddle.net/trollixx/qj2YK/
The main condition is vertical scrollbar in selectmenu's dropdown.

**Comment by fnagel** [comment]
Issue confirmed, no idea why I did not notice this one :-( Thanks a lot!

This only occurs if a auto maxHeigth is set. This happens if there are many options before refreshing to less options.

Should be fixed as I improved the whole height & maxHeight algorithm. Please test latest version and give feedback!

Related to: https://github.com/fnagel/jquery-ui/issues/26

**Comment by trollixx** [comment]
Cool, everything works like it should! Thanks for fix)

**Comment by fnagel** [comment]
Closed, please reopen if needed.
