### ISSUE TITLE
Make selectmenu update contents with ajax

### ISSUE THREAD

**Issue by sezaru** [fnagel/jquery-ui#17]
hello, I have some select menus in my website that are dinamics, for exemple, let me say that I have a select with some countries, when the user select a contry, the state select menu need to change to show de states of this country, there is some way to do this?

Thanks!

**Comment by fnagel** [comment]
You could use the select callback. Please take a look at the ajax demo: http://github.com/fnagel/jquery-ui/blob/selectmenu/demos/selectmenu/ajax.html

Does this work for you?

**Comment by phazei** [comment]
Should/can the plugin monitor the select box and see if options have been added/removed?  Say if the options dynamically change based on checkboxes or something.

**Comment by fnagel** [comment]
Mhh perhaps a option to add or remove a item would be more suitable. With some callbacks.
Would be a nice feature. What do you think.

**Comment by dannycohn** [comment]
Instead a 'refresh' function (similar to that of jQuery UI's button) should be added that makes sure the fancy UI is in sync with the underlying element.

**Comment by fnagel** [comment]
Nice idea. So we only need to add an option to the original select element.
Should be doable as we could split the create function into a jQuery UI widget factory based _init function. 
I will take a look in a week I guess. Im currently working on somethign else. Thanks for all your support and contribution!

**Comment by mad-doctor** [comment]
Hello, any progress on this issue? I'm stuck with an order form for a website with exactly the same problem (dynamically changed options). The first thing that came up in my mind was the button refresh method. Any chance for this to be added in the near feature? :(

**Comment by fnagel** [comment]
I'm working on this, please be patient. I already implemented this feature in a dev version but it's not usable yet. Most work is done, but this needs major refactoring. 

ps: I will use the _init and _create methods of the jQuery UI Widget Factory. See http://jqueryui.com/docs/Developer_Guide for more infos.
We will use : 
     $('select#myElement').selectmenu();
to refresh from the original element.

**Comment by fnagel** [comment]
Please check out the latest commit and give feedback as I made a lot of testing but not quite sure if everything works out.

ps: Its possible to re-new almost all options too.

**Comment by mad-doctor** [comment]
Great job!! I've tested it, and so far it's working as expected!
However I've noticed another small problem, not sure it's worthed opening a new issue for this - when you're hovering above the selectmenu, and you disable it, the ui-selectmenu-focus and ui-state-hover are not removed. I've reported a similar issue some time ago, but then the problem was that the hovering worked even if the menu is disabled.

I'm solving it like this:

$("#menu").selectmenu("disable");

$("#menu-button").removeClass("ui-selectmenu-focus ui-state-hover");

but it will be more convenient when "disable" is called, the above classes to be removed automatically.

Also a small CSS problem - IE6 does not support transparent border and when you open the menu, all LI's have dashed borders around them. The solution for IE6
.ui-selectmenu-menu li{border-color:fuchsia;filter:chroma(color=fuchsia);width:100%;}

Unfortunately, I have no place to upload a demo for this issues :(

**Comment by fnagel** [comment]
Thanks for your feedback!

There are a few open issues about the disable problem (single option, on-the-fly, initial). I will rework this asap as there a few helping posts about this issue.

There is are few IE6 issues like the icon positioning problem. I opened a report for this (already known) issue: https://github.com/fnagel/jquery-ui/issues/issue/50

**Comment by mad-doctor** [comment]
I saw the workaround for the IE6 transparent borders, but it will not produce valid css, \* html is classified as a css hack. I'm not sure to what extend this is important, but can we just use a border-color with the same value as the background color of the list? Something like:

var thisLi = $(<li.....).css("border-color", this.list.css("background-color"))..

Just some thoughts...

Meanwhile I'm continuing my tests of the new refresh functionality, again, thank you very much for it!

I'll try to upload a working demo of my "disable" issue.

**Comment by fnagel** [comment]
I think the Star Hack should be ok as its used in official jQuery UI widgets, too. See jQuery UI CSS Framework base or the autocomplete widget.

**Comment by fnagel** [comment]
Closed as issue is solved. Please open a new issue if any problem with the new feature occur.
