### ISSUE TITLE
Discussion about additional wrapperElement required

### ISSUE THREAD

**Issue by thg2k** [fnagel/jquery-ui#175]
Hi fnagel, I'm using your selectmenu widget on a production website.

After 4 months I came back to your repository to merge latest changes, but the current version (ok it says "dev version" in the header but still..) completely borked my web site, so I had to revert to the previous version from around june 2011.

My main problem now is that you added this "wrapperElement" option which defaults to "[div /]", but there is no easy way to remove it.
I have a lot of selectmenus around my website and I don't need to add additional complexity to the markup so I wanted to disable it, but the way your code currently handles it makes it difficult to remove it.

So my question in the end is.. do you have any real testcase why this option is needed? If I want to wrap I can just wrap my [select], then when I call selectmenu() it will .insertAfter() in the right place so the result is the same... plus the it is already wrapped inside as [a][span/][span/][/a], so I really don't see any need to add an additional [div].

Also second question, do you think it's time to maintain a stable branch? With the current state I cannot afford to merge it in my production site if I have to spend several hours debugging problems each time :(

**Comment by fnagel** [comment]
It says dev version because its the dev version :-) I will always push my latest changes to the branch and release tagged version from time to time. I will release a new tagged version soon (hopefully).
If you like you could test out the new, built from scratch version which will be intergrated in jquery UI. See #140

The wrapperElement is needed as the position plugin is not able to handle a ul probably. Another use usecase is CSS scope when using different styles on the same page.

Please note: there was another issue about making Selectmenu more usable #172

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Please give feedback!

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen if needed.
