### ISSUE TITLE
highlighting and focus indications

### ISSUE THREAD

**Issue by phazei** [fnagel/jquery-ui#19]
There seems to be an issue with mouseout where it doesn't remember the highlighting state before mousein.

--If you tab through some select boxes, then move the cursor across it, on mouseout it loses the blue highlighting that it had a moment before.

--If you click the box, the click again to close and move the mouse away, it's still focused, but it loses its highlighting.  Though I noticed if I navigate away from the page then back, it's highlighted again.

--If a menu item is selected and you click the menu, the selected item is orange, if you mouse over that item then move the mouse out of the box to the left or right, it loses orange highlighting until you move mouse back into box.

**Comment by tuzemec** [comment]
I've looked into this. It's caused by removing of the "activeClass" from _selectedOptionLi on "mouseout" event on each LI. 
The activeClass is added again when you hover/focus another LI. But when you are leaving the _selectedOptionLi and heading outside the UL there's no one to set the activeClass again.

I think that the quickest fix is to bind "mouseout" on the list itself immediately after UL creation. For example we can put the following code on line 137:

```
this.list.bind("mouseleave", function(e){
    self._selectedOptionLi().addClass(activeClass);
});
```

It works for me, but can somebody confirm that? 

Anyway... this solution feels kinda dirty. I think that the LI's mouseover / mouseout / focus / blur routine have to be revised. Probably separating the mouse events from the keyboard ones will be a good start. I'll try to come up with some solution.

**Comment by fnagel** [comment]
Could somebody please confirm if this problem is still extisting?

**Comment by fnagel** [comment]
Closed because of no feedback given. Please reopen if necessary.
