### ISSUE TITLE
Keyboard controls break with jQuery 1.7

### ISSUE THREAD

**Issue by vincentlepes** [fnagel/jquery-ui#196]
Using up and down arrows to select options when menu is expanded works when using jQuery 1.6.2 as provided with the download, but no longer works when jQuery is updated to 1.7.  Arrows still work to select options from collapsed select menus, but when they are expanded to show more options the arrows become useless.  In selects with many options, expanding is essential for usability.

**Comment by fnagel** [comment]
There is a new, built from scratch version for jQuery 1.7.x which will be released with jQuery UI sometime. This branch will not support 1.7.x but I will maintain this as a legacy version for 1.6.x as long as its needed.

Plese take a look here: #140
Note: there a currently some issues with the new version due to changes to Menu widget.

**Comment by vincentlepes** [comment]
Thanks for following up so quickly :)

**Comment by fnagel** [comment]
No problem :-)

Question solved?

**Comment by vincentlepes** [comment]
Yes, thanks
