### ISSUE TITLE
select boxes side by side

### ISSUE THREAD

**Issue by phazei** [fnagel/jquery-ui#20]
Since the anchor tag is set to display:block, if you have select boxes next to eachother, they stack instead.  display:inline-block fixes this, but it's not backwards compatible.
select boxes are inline by default, so they should be that way with this plugin.

**Comment by fnagel** [comment]
With backwards compatible you mean that older browser cant deal with it, correct?

What is your solution for this? When I set it to inline the visual styling of the widget breaks.

**Comment by phazei** [comment]
Yes, older browsers don't support "inline-block", ie6 specifically.

The solution would be:
For most browsers:
display:inline-block;

IE6/7:
*display:inline; 
zoom:1;

FF2:
display:-moz-inline-stack;

Though I haven't tested it in IE6.  Ideally it should possibly restructured, but that would be a much bigger pain.

**Comment by fnagel** [comment]
I will take a look at this soon. Needs some testing in different browsers, thanks for posting the CSS snippets.

**Comment by syhc** [comment]
the solution seems to be: 
.ui-selectmenu { display: inline-block; position:relative; text-decoration: none; overflow:visible;}

You also have to set overflow to be visible (over hidden) or else they don't align with the buttons either, it floats up. The solution works with ff 3.6.9, opera 10.63, and chrome 8. However it still doesn't work with IE 8 (both 32 and 64 regardless of compatibility). Also, height is not needed.

In regards to inner-block, if you look at JQuery UI button in CSS they also use it. I don't want to say we should not make it backwards compatible but it is not a huge priority isn't it? I guess some standards need to be clarify (or i haven't found the document on it)

Further, in order to have the same height as buttons (if you want to put it side by side with buttons), this line should be changed:
.ui-selectmenu-menu li a,.ui-selectmenu-status {line-height: 1.4em; display:block; padding:.4em 1em; outline:none; text-decoration:none; }

the padding should be change from .3em 1em to .4em 1em to be consistent with the buttons

**Comment by fnagel** [comment]
@syhc 
Im sorry, but your snippet breaks some options (format for multiline formatting) and has a few other issues in different browsers. Additionally Im not willing to break older browser support.
Ive change the size of the selectmenu to match the current jQuery UI button style.

After extensive testing I must confess Ive not managed to built a fully working cross-browser version. FF2 does not show the icon if I use the snippet (-moz-display-stack or box from phazei) as it breaks the position of absolute elements (aka the icon) within a parent relative positioned element. Strange enough it works nice in IE6. Ive decided to drop inline display support for FF2 because this did not work since yet, so... Should work for all other browsers as I tested this in latest FF3 and 4 beta7, latest Opera and Safari and IE6, 7 and 8 (virtual machine).

Please check out the latest commit and give feedback!

**Comment by fnagel** [comment]
Please give feedback on this issue!

**Comment by revsystems** [comment]
Not sure if you consider this an issue, but text surrounding a selectmenu is vertically aligned to the bottom in Firefox/IE, but not Chrome. You should be able to add vertical-align:middle to .ui-selectmenu so it is consistent across browsers.

**Comment by fnagel** [comment]
Would you please help me do understand this by providing an example? This could be done very easy using this: https://github.com/fnagel/jquery-ui/issues#issue/61

**Comment by revsystems** [comment]
Sure, sorry about that.

Browser: Firefox 3.6.13, IE 7-9 (tested)

I updated http://jsfiddle.net/hsn95/14/ to add some text around it so you can see what I'm talking about.

If you view in Chrome, you'll see the text is vertically aligned to the middle. In Firefox, it is vertically aligned to the bottom. It aligns to the bottom in IE too, but jsfiddle doesn't seem to work with my IE9, so I'm not sure if you'll see the issue there.

**Comment by fnagel** [comment]
This needs some more testing in all supported browsers to ensure there are no side effects. I will add this to the v1.1 ToDo list. Thanks for your help.

By the way: https://github.com/fnagel/jquery-ui/issues/issue/70

**Comment by fnagel** [comment]
Ive added     vertical-align:middle and pushed the changes to GitHub. Thanks for your contribution. 

Please open a new issue if there are any further problems with lacing selectboxes side by side.
