### ISSUE TITLE
IE7 IE8 selectmenu stops working when clicked 

### ISSUE THREAD

**Issue by chernobil** [fnagel/jquery-ui#228]
Hi, the problem appears when using jquery 1.7.1 and select menu in IE7 and IE8 . 

The problem is that the select menu stops responding when clicked if at that time there is another event that have to be handled. 

Here is the demo http://jsfiddle.net/GXtpC/429/. 
Way of reproduction 
1. Type something in the input that says "ChangeMe and press the selectmenu"
2. Press the select menu 

note: It is important that the focus out (of the input) to be made with the click on the selectmenu. The inputs change event and select menu click should fire at the "same" time

**Comment by fnagel** [comment]
jQuery UI 1.7.1 is currently not supported. Any help is appreciated! 
Please see here for similar issues: https://github.com/fnagel/jquery-ui/issues?labels=Update-jQuery-version&state=open

**Comment by chernobil** [comment]
An useful answer.
When is expected jQuery UI 1.7.1 to be supported ? Are there any estimations ?

**Comment by fnagel** [comment]
I have no idea. I will work on this asap but any help is appreciated.

I have only a certain amount of time to support this effort and will allocate it the best I can. It is possible speed up development or a fix for your specific problem by placing a donation.

**Comment by fnagel** [comment]
Ive updated Selectmenu to jQuery 1.7.2 and jQuery UI 1.8.20. There are some issues left, like fixing typeahead (see #213, help is appreciated!).

A general (not jQuery version related) problem with positioning in older IE was fixed before updating. This problem was introduced with the appendTo option and therefore only affects newer version of Selectmenu.

Please test latest commit and give feedback!

**Comment by zuormo** [comment]
Hello Everyone,

I've found something and maybe this can help in the solution of the bug in IE 8. The problem raise only when select is inside a form tag. I've tried to implement my page without the form tag and all the script had work perfectly (load, change and raise callbacks).
So I suppose that the problem is just in that situation... I wil try to debug more and If I'll find something I'll post again. Thank you

**Comment by fnagel** [comment]
@chernobil 
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by chernobil** [comment]
Looks Ok 10x :)

**Comment by fnagel** [comment]
Nice! Thanks for your feedback!
