### ISSUE TITLE
Selectmenu hide method

### ISSUE THREAD

**Issue by ghost** [fnagel/jquery-ui#245]
I noticed the selectmenu plugin uses the hide() method for hiding the original <select> element. While this works in most cases, it can be problematic when trying to use the plugin with some other useful plugins - most notably jquery.validate.

I suggest replacing 

```
    // hide original selectmenu element
    this.element.hide();
```

with

```
    // hide original selectmenu element
    this.element.addClass('ui-helper-hidden-accessible');
```

as it seems that's how the jquery.ui.button plugin does things with the backing checkbox. The added class visually hides the element while still making it accessible to other plugins.

**Comment by fnagel** [comment]
Sorry, but I wont change this.

It would lead to a11y problems (both elements, the new and the native would be recognized by screenreader) and this widget is meant to be accessible. 
Its a general problem of the validation plugin and could be easily fixed by adding a line of code by yourself (perhaps within a
callback).

ps: hide() will be used in the official jQuery UI Selectmenu widget too!

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by ghost** [comment]
Oh sorry, I thought you had closed the issue. 
Well I changed the code to use the css method as it was easier in my case. I wouldn't know about accessibility issues, so I'll leave you to decide that.

Thank you for the support.

**Comment by fnagel** [comment]
Nice to hear you fixed your problem. Thanks for the feedback!
