### ISSUE TITLE
calculate a default auto height

### ISSUE THREAD

**Issue by michaelcaplan** [fnagel/jquery-ui#26]
When the dropdown doesn't fit into the available space below or above, a scroll solution is needed.  Without such a solution, the selectmenu can only be used in select circumstances and cannot be a general replacement for select elements.

**Comment by tauren** [comment]
I think this should be a CRITICAL bug. The selectmenu needs to always fit within the viewport, but the way it is now, it can easily flow off the screen.

I've attempted to reduce the problem with some CSS:
.ui-selectmenu-menu {max-height: 300px}

However, that really only works when the selectmenu is in the middle of the screen, not near an edge and the screen is about 600px tall or more.

Also, it only works when the menu is displayed the first time. If you scroll and select something else, then show the menu again, it is positioned in the wrong place on the screen, and will often have part of it not be visible.

I'd try to work up a demo soon.

**Comment by tauren** [comment]
Here's a sample of the problem:
https://github.com/tauren/jquery-ui/blob/selectmenu/demos/selectmenu/positioning.html

The strange thing is that the problem seems to happen based on where the selectmenu is on the screen. The first select works fine even with maxHeight set. The second select is the exact same as the first, but it has problems.

If I add some &lt;BR&gt; tags before the &lt;FORM&gt; tag, then even the first selectmenu has problems.

I haven't starting debugging this yet to see what is causing the problem.

**Comment by tauren** [comment]
Turns out that the problem I was experiencing was because selectmenu wasn't properly handling optgroups. It was finding the height of all LI tags, but some of those LIs were actually optgroups and were very tall, throwing the position off.

I've fixed the problem here:
https://github.com/tauren/jquery-ui/blob/selectmenu/ui/jquery.ui.selectmenu.js

I'll send a pull request, as I'm sure this will help others wanting to use optgroups.

**Comment by fnagel** [comment]
@michaelcaplan
Within my FF the popup always opens in the direction with enough space and has a inline scrollbar. Are you sure to use the latest commit?

**Comment by fnagel** [comment]
Did you tried the maxHeight option?

**Comment by michaelcaplan** [comment]
@fnagel, I'm using the latest commit as of 14 days ago.  I'll update, to be sure.  What I see in FF is the dropdown either opening top or bottom with no scroll bar.  maxHeight changes the game, but having to set that adds a level of complexity with variable screen sizes.

**Comment by fnagel** [comment]
So maxHeight solves you problem? 

Im sorry you dont like the maxHeight option but Im not sure what could be better. Any idea?

**Comment by michaelcaplan** [comment]
No, maxHeight is a fine option.  But, if the goal is to have a drop in replacement for select elements, I'd want maxHeight auto negotiated based on available screen sizes.

Looking at it from this perspective, I'd say this is a more of a feature request (consideration), than a bug.  maxHeight provides a workable solution to the problem of long lists.  It's just not optimal.

**Comment by fnagel** [comment]
I will implement this feature as I consider it as very useful. What would be the perfect default max height? 1/4 of the viewport?

**Comment by fnagel** [comment]
I commited a fix with 1/3 vieport height as default auto height. Uselatest commit as I needed to disable this for selectmenus with address formatting.

**Comment by fnagel** [comment]
Seems to be fixed. Please reopen if necessary.

**Comment by fnagel** [comment]
Some changes which could end up in some kind of regression: 
https://github.com/fnagel/jquery-ui/issues/133
https://github.com/fnagel/jquery-ui/commit/b2d02482fa950cb51524312e4b2ec43a6eacee46
