### ISSUE TITLE
Need to change opening direction under certain circumstance

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#3]
This could be needed if theres not enough room, for example when the widget is placed at the very bottom of a page.

**Comment by fnagel** [comment]
http://wiki.jqueryui.com/Selectmenu#commentnum1269874936

**Comment by fnagel** [comment]
Since commit http://github.com/fnagel/jquery-ui/commit/cde0d9042c95508d04cfa6d96d8e426657e23523 the widget checks if there's enough room to expand to the bottom, otherwise expand to top.

Its not perfect but acceptable if we keep performance in mind. Im open to improvements!

**Comment by fnagel** [comment]
This should be done by position functionality as its already checks available room. This should make positioning more fault-tolerant and should remove unnecessary  code.

See http://jqueryui.com/demos/position/

**Comment by phazei** [comment]
I'd say this is a bug rather than a feature.
If an item is at the top, but the last item in the list is selected, it opens upwards and there is no way to see the options.  This makes it non-functional.
I'm using the latest version as of today.  This is still an issue for select boxes at the top.  It seems to be fine on the bottom.

EDIT:
This seems to fix it temporarily, position would be better:
        if ((menuTop + listHeight) > (viewportHeight + pageScroll)) {
            menuTop -= listHeight;
        } else if ((menuTop - pageScroll) < (listHeight)) { //check top
            menuTop += this.newelement.height() + 4;
        } else {

**Comment by fnagel** [comment]
As it was implemented without position originally this seems to me as a feature -- but naahh who cares: we just need to improve it :-)

Thanks for the quick and dirty fix. Should be fine for the bottom as I tested this for my own project.

Will be commited soon!

**Comment by bluefox** [comment]
In the latest code (2010-10-25), I noticed the following line 

// needed when window is resized
$(window).resize(function(){
self._refreshPosition();
}); 

I believe this line is not needed since _refreshPosition will be called in open.

Also I noticed that _refreshPosition is invoked twice in open function, is it intended? If it is, what was the purpose?

**Comment by tauren** [comment]
The positioning problems are the main showstopper for selectmenu right now. All the extra fancy features should wait until this is solved. If we can't reliably create a basic select replica and have it always be on the screen, then I consider it to be a CRITICAL bug.

Positional problems is what the position plugin is intended for -- to help make sure UI elements stay on the screen. I think it would be WELL worth the extra work to convert selectmenu to use position. Otherwise, we'll end up redoing a lot of what position already does, and won't have nearly as many eyeballs finding problems with the positioning logic as there are using the position plugin.

**Comment by tauren** [comment]
Here is a demo that shows a positional problem:
https://github.com/tauren/jquery-ui/blob/selectmenu/demos/selectmenu/positioning.html

I explain it further in issue #26 (Long Dropdown)

**Comment by fnagel** [comment]
You're absolutely right. This needs to be fixed asap. I will implement the position plugin as I mentioned above. Please see: https://github.com/fnagel/jquery-ui/issues#issue/3/comment/438301

I was pretty busy as I worked on an TYPO3 extension but now I will allocate some time to fix this issue.

**Comment by tauren** [comment]
fnagel: no worries -- you have a life just like we all do!

Before you start, please take a look at my repo. I've fixed the main positional problem I was having and you may wish to simply pull this fix into your repo.
https://github.com/tauren/jquery-ui/blob/selectmenu/ui/jquery.ui.selectmenu.js

This fixes a problem with positioning popups that include optgroups. This is explained further in issue #26.

**Comment by fnagel** [comment]
@bluefox 
Im pretty sure this line is needed in certain cases.
We will use position plugin soon (hopefully).

**Comment by fnagel** [comment]
I've already have a working version with position support, but I need to implement optiosn like style:'dropdown'. I'm currently thinking of the style option as a pure CSS switch and a positionPara option to overwrite the default positioning. This way it would be possible to use any positioning you like!

Give me a few days...

**Comment by fnagel** [comment]
Please check out the latest commit. I've implemented the jQuery UI position plugin. Any feedback is appreciated. 

I will wait for feedback and close this issue soon.

**Comment by fnagel** [comment]
Closes, as this problem seems to be fixed.
