### ISSUE TITLE
Nesting issue with JQuery Tabs

### ISSUE THREAD

**Issue by seeclarencerun** [fnagel/jquery-ui#58]
Great job on the select menu but we did run into a problem where it seems to not work when the select menu is called within a tag that is NOT the first JQuery tab. When in the first one it opens properly. When nested into the second or third tab the select is there but the width is set to 1px.

**Comment by fnagel** [comment]
Did I get you right that there is a problem when using the selectmenu widget in the jQuery UI Tabs widget within a tab-panel that is not the first one?

Did you try to init the selectmenu with a fixed width? Width calculation is based upon $.width() / $.outerHeight() which fails (afaik) when used on hidden elemenst (like the non opened tabpanel)

Another solution could be to inti the selectmenu widget when the tab is firstly opened? Could be related to a problem

**Comment by rmullaney77** [comment]
Issue confirmed

It is not however a 'first tab' issue. Will happen with any non-visible tab content that has a selectmenu during init.

#### Example Code:

https://gist.github.com/raw/804697/9f8f34d04683355916dde01a98357a4c7f43e734/html5-selectmenu-tabs-bug

Issue occurs in modern IE, FF and WK browsers (did not test opera)

**Comment by fnagel** [comment]
Did you tried my suggestions? Seems to be we posted same time...
...and your comments seem to confirm my thoughts above.

**Comment by rmullaney77** [comment]
Problem solved, though this is still a valid bug i think. Make your call to selectmenu before initializing the tabs. eg:

```
$('select').selectmenu();
$('div.tabs').tabs();
```

Does not work if the tabs are initialized before selectmenu

**Comment by rmullaney77** [comment]
Yes, i tried explicitly setting the width and that had no effect on the non-visible selects. Not sure if I should refer to it as a bug, rather a limitation ;)

**Comment by fnagel** [comment]
Thanks for pointing that out. Perhaps we could take a look at how the width are calculated and ensure the widget uses only the option defined width. The :visible selecor could be a useful helper.

This is considered as a low priority issue as there are a few more important ones.

**Comment by rmullaney77** [comment]
Since there is an easy workaround (above) I assumed it would be low priority :)

**Comment by revsystems** [comment]
Hi,

This issue is because jQuery reads the width/height of an element as 0 if its parent is hidden (strangely, it gets the right height if only the element in question is hidden). I think the correct behavior in this context is kind of ambiguous.

I wrote a plugin called [jQuery-Peek](https://github.com/revsystems/jQuery-Peek) which could be used to get around the problem. After you include it, you would initialize it like:

```
$("div.tabs").tabs();
$("select").peek("selectmenu", { options if you want... });
```

That would ensure `select` is js-visible when selectmenu is initialized.

@fnagel: If you want to fix it without using peek, you need to move the original `select` to a non-hidden context, e.g. the `body` tag, get the width, then move it back. The issue with that is, if the `select` css is context senstive, it will obviously get the wrong values.

**Comment by fnagel** [comment]
Perhaps I will install your fix as a optional "add peek class if needed" functionality. What do you think?

**Comment by revsystems** [comment]
Not sure how you'd want to do the include. The license for jQuery-Peek is a slightly modified MIT--you can use it with no restrictions, but you'd need to include the RevSystems attribution line and URL somewhere in the source. If that's okay with you, then I'm fine with that. If not, then maybe just a quick link and description of the problem in your Readme might work.

Feel free to message me if you want to talk more about this.

**Comment by fnagel** [comment]
I think I did understand you wrong. All I need to do is add your JS file, and init the selectmenu within the tabs like you posted in your snippet above and everything works out. So a "Known Problems" section in the wiki with a description and the snippet should be a suitable solution for this issue. Right?

**Comment by revsystems** [comment]
Yes, I think that would be a good way to handle it.

**Comment by fnagel** [comment]
Ive updated the Wiki. Please reopen if necessary.

**Comment by alesnav** [comment]
Sorry for reopen, but I have a problem with this.

I am using Fancybox, but the problem is the same than tabs. I must init selectmenu this way:

$("select").hide();
$("select").peek("selectmenu", { inline: true });

The first line is needed because selectmenu function initialized from peek won't hide select elements on the page.

My second question (I tried to get it done, but I couldn't :( ) is: how I can change the value of a select that is already hidden.

I tried with:

$('select#fsector').selectmenu("index", 0);

And it changes the value, yes, but visually it does not select the value. Then, I tried to do it using Peek... but I don't know how to use it for this purpose...

Any idea?

Thanks!!
