### ISSUE TITLE
Destroy method needs some work

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#7]
Andreas asked: "it would be nice if "destroy" would return the element itself (return this) at the end, at least I have used it once."

Im not sure about this. For what do you need this?
I checked different UI widgets, every single one uses a different one:

<pre>return this</pre>

<pre>return $.Widget.prototype.destroy.call( this );</pre>

<pre>$.Widget.prototype.destroy.apply( this, arguments );</pre> This is the recommended way described in http://jqueryui.com/docs/Developer_Guide

Some even do nothing. What is best practice?

**Comment by fnagel** [comment]
Additionally some not events are not removed. 
Edit: done, see http://github.com/fnagel/jquery-ui/commit/8b271ae39fad7817dba571c3c562a2de5042ebbd

**Comment by adoerler** [comment]
> Im not sure about this. For what do you need this?

I think the main use would be the chaning functionality. So you could use for example $('#test').spinner("destroy").hide();

I read the uptgrade guide again (http://jqueryui.com/docs/Upgrade_Guide) and now I'm not sure if it is really needed anymore. It says: "Getter methods no longer need to be explicitly defined. Any method that returns a value other than undefined or the plugin instance is automatically treated as a getter. This also adds the ability to define a method that can act as a chainable setter and a getter.". 

And "A new common method has been added, called widget. This method will return the .ui-{pluginname}  element. Depending on the plugin, in many cases this is different than the original element, otherwise it will return the original element."

This would mean, that the element is returned automatically if nothing else is specified.

**Comment by fnagel** [comment]
I think your right, Ive tested changing and it works in the current version without the above mentioned snippets. But Im not quite sure if its useful in some other way. I will try to ask Jörn Zaefferer, perhaps he knows what to do...

**Comment by jzaefferer** [comment]
If the Widget destroy method covers all cleanups, you don't have to implement it yourself. Otherwise, define the method on your widget, call the Widget implementation (see above) and do your own cleanups afterwards (or the other way round, doesn't matter).

Don't return anything, then the chain won't break.

**Comment by fnagel** [comment]
Thanks for that info Jörn. So all I need to do is clean up my own mess and use Widget implementation which is:

<pre>$.Widget.prototype.destroy.apply( this, arguments );</pre> 

This code is from jquery.ui.progressbar.js but as far as iI can see arguments is undefined.

**Comment by jzaefferer** [comment]
aruments is implicitly defined in a function scope. Just console.log(arguments) within any function to se for yourself.

**Comment by fnagel** [comment]
Thanks for making this clear. This is already commited.
