### ISSUE TITLE
Integrate with jQuery UI menu widget

### ISSUE THREAD

**Issue by fnagel** [fnagel/jquery-ui#78]
Link to a working version: https://github.com/petersendidit/jquery-ui/tree/selectmenu

Thanks David Petersen! 
Mentioned here: http://twitter.com/#!/petersendidit/status/34040749318209537

**Comment by fnagel** [comment]
I really love to use the menu widget within the selectmenu plugin. I did not work with menu widget before so would you please describe what you did? And what about the integration? Are there some pros and cons? Is the selectmenu widget slimmer / faster / more stable? Do all features work like before? What browser did you use for testing?

**Comment by petersendidit** [comment]
Most of the work was to take out the code inside of selectmenu that created and handled the menu and let it use the jQuery UI menu plugin that already did most of what selectmenu already needed.  The menu plugin has been updated greatly since I did my work which I think will make it even easier to make selectmenu do all that it needs to do with the menu. 

My code probably is a good place to look but it might be best to start fresh with a current version of the selectmenu and the menu plugin and go from there.  If I have any time in the next week or so I might be able to dig back in to this. But we will see.

**Comment by fnagel** [comment]
Im sorry you fork is outdated because of my late response. I promise I will pull your changes faster this time :-)

Please try to leave a comment here when you start working on this issue. 
Your contribution is really appreciated!

**Comment by fnagel** [comment]
Please take a look here: https://github.com/fnagel/jquery-ui/issues/140

**Comment by fnagel** [comment]
Im sorry to inform you that this feature wont be included. As there is a new version of this plugin (see #140) which will hopefully be included in jQuery UI 1.9. Its built from scratch and most of my time will be used maintaining the official version.
Please note that this version makes use of jQuery UI menu and is already ready to use.

This branch will be maintained but with focus on bugfixes.
